### PR TITLE
Add error checking for registering users via CSV

### LINKED ISSUE #127: CSV upload needs proper error reporting
When running the test to upload users via CSV the test should stop at the first error, display the actual error and shouw all that was parsed before the error occurred

### PR DESCRIPTION
**Pull request by egeldenhuys**
Requires PR #162 for Python 3.6

### Added
- `csv_utils` module for CSV validation functions, including

### Changed
- Error handling for registering users via CSV (closes #127)

### Features
- Add users from CSV
- CSV example text
- Display error when:
  - A user already exists
  - There are duplicate `user_id`s in the CSV
  - The CSV does not contain the correct headers
  - A field for a row is missing

### Notes
- Only subsequent duplicate ids are displayed
- Uploaded CSV files that are not confirmed or cancelled are not deleted
- CSV files are expected to be uploaded to the hard coded path `media/documents/'

### Screenshots
Base component:
csv_1

Preview
csv_2

Success
csv_3

User(s) already exist
csv_4

Duplicate `user_id`
duplicates

CSV syntax error
csv_5

CSV Example:
csv_example

### CODE REVIEW

**Comment by egeldenhuys** [comment]
Will implement that now

**Comment by egeldenhuys** [comment]
Also note that this PR requires Python 3.6, is this acceptable?

**Comment by devosray** [comment]
@egeldenhuys Yes, we will be migrating the project to Django 2 and Python 3.6 before #139

**Comment by egeldenhuys** [comment]
@devosray, duplicate `user_id`s are now reported
duplicates

Requires #162 for Python 3.6

**Comment by egeldenhuys** [comment]
csv_example

**Comment by devosray** [comment]
Seems OK

**Pull request merged**
