### PR TITLE
Move question grouping 43

### PR DESCRIPTION
**Pull request by nigelmpofu**
# Changelog #43 

### Question grouping is now selected in the questionnaire builder

- Changes to model
- Improvements to the UI
- Fixed questionnaire preview

### CODE REVIEW

**Comment by devosray** [comment]
Request my review when you are ready to merge; just fix the merge conflicts first :D

**Comment by devosray** [comment]
Small issue: Pressing the enter key on the label editing page submits the questionnaire. It's annoying but not critical. If it is easy to fix, please look into it.

image

**Comment by devosray** [comment]
What about the possibility of editing the labels for a question? Or at least viewing the current labels? Currently you can't view the labels you have assigned to the questionnaire (not that I know of)

**Comment by nigelmpofu** [comment]
I'm still working on that functionality, just wanted to get the testing started as it's a major change and might have a few bugs

**Comment by devosray** [comment]
Awesome. Looks really good so far, I'm pushing a bugfix to your branch

**Comment by devosray** [comment]
**BUG:** Adding a new question to an existing quistionnaire changes all existing questions' groupings to "rest"

image

**Comment by devosray** [comment]
**BUG**: Setting the grouping of multiple questions to "label" results in all of the questions having the last labels entered.

image

**Comment by nigelmpofu** [comment]
Let me look into that label bug

**Comment by devosray** [comment]
I have made some changes to simplify the question groupings when you start a fresh database. Please see pull request #167

**Comment by nigelmpofu** [comment]
I have fixed all major bugs and ready to merge :smiley:

**Comment by devosray** [comment]
Looks good! Thanks for the feature.

**Pull request merged**
