### PR TITLE
Questionnaire label edit 169

### PR DESCRIPTION
**Pull request by nigelmpofu**
# Changelog #169 

- Added functionality to view and edit labels in questionnaires
- Moved the edit warning to the edit page #171

### CODE REVIEW

**Comment by devosray** [comment]
The new warning page looks good :+1:

**Comment by nigelmpofu** [comment]
Let me investigate that

**Comment by nigelmpofu** [comment]
I looked into it and the issue and it seems to be a backwards compatibility error caused by questionnaires that were created before the recent changes to the model were applied. All new questionnaires after the changes are not affected. To fix the older questionnaires, they can be deleted and done again _or_ editing the existing one by deleting (**not editing**) the label questions and re-adding them. I also added a safety check to prevent the saving error just as a precaution.

**Comment by devosray** [comment]
@nigelmpofu Ah I see. After creating a new questionnaire, I can edit labels. Fantastic!

**Comment by devosray** [comment]
@nigelmpofu One more problem (sorry for nitpicking haha). It seems like adding a new question with labels after editing another question's label results in the existing question's labels being edited.
Steps to reproduce:

1. Create a new question with some labels.
2. After adding it, change its labels by adding/removing a label
3. From the "select questions" dropdown, insert a new question with the label grouping.
4. Press the '+' button to add a label to the to-be-added question.

If all goes "well", you will be editing the labels of both the existing question and the new one. The existing question's labels will be copied into the new question's label area.

**Comment by nigelmpofu** [comment]
Small issue but I've managed to fix it :smiley:

**Comment by devosray** [comment]
@nigelmpofu I can confirm that the issue has been fixed and from my testing, everything seems good. Let me know when I can merge :+1:

**Comment by devosray** [comment]
I'm merging the pull request for testing. Just reopen it if you still wanted to add stuff to it.

**Pull request merged**
